# ApacheインストールPlaybook

- hosts: all
  become: true
  tasks:
   - name: apt でApacheインストール
     apt:
       name: apache2
       state: present

   - name: Apacheの起動とchkconfig登録
     service:
       name=apache2
       state=started
       enabled=yes

